services:
  plandex-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PLANDEX_DB: $PLANDEX_DB
      PLANDEX_USER: $PLANDEX_USER
      PLANDEX_PASSWORD: $PLANDEX_PASSWORD
      #PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - $PGDATA_DIR:/var/lib/postgresql/data
    networks:
      - plandex-network
  plandex-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - "$PLANDEX_DATA_DIR:/plandex-server"
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://$PLANDEX_USER:$PLANDEX_PASSWORD@plandex-postgres:5432/$PLANDEX_DB?sslmode=disable"
      GOENV: $GOENV
      PIN2LOG: $PIN2LOG
    networks:
      - plandex-network

networks:
  plandex-network:
    driver: bridge
